### ISSUE TITLE
Digital output missing from Tracklet pattern reco

### ISSUE THREAD

**Issue by tomalin** [cms-L1TK/cmssw#101]
In the HYBRID_NEWKF chain, data is passed between the tracklet pattern reco & KF via the TTTrack & TTStub classes. These do not contain digitized data, digitized according to the expected format at the output of the tracklet pattern reco. This KF therefore has to make it by digitizing the floating point TTTrack & TTStub data. This may lead to bit errors when comparing to FW.

Solution: If Hybrid running with "fakefit" option, the tracklet pattern reco should output a new EDProduct with the digitized track & stub data from the TrackBuilder, with pointers to the corresponding TTTrack & TTStub objects.

N.B. The existing "Tracklet" class does contain digitized helix param & residual info, but only for one stub per layer per track. 

Comment comes from @tschuh

**Comment by tschuh** [comment]
solved with https://github.com/cms-L1TK/cmssw/pull/111
