### ISSUE TITLE
Stub collection issue running new KF

### ISSUE THREAD

**Issue by cgsavard** [cms-L1TK/cmssw#184]
An error occurs when running through some samples with the new KF associated with the stub collection. Here is the error message:
![image](https://user-images.githubusercontent.com/15660721/188674480-84afe9de-3bca-4f51-82d7-a8712b5bc230.png)

This can be reproduced by using this (formula)[https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1TrackSoftware] to create a fresh CMSSW release, setting the (L1TRKALGO)[https://github.com/cms-L1TK/cmssw/blob/L1TK-dev-12_5_0_pre2/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker_cfg.py#L20] to "HYBRID_NEWKF", and then running "cmsRun L1TrackNtupleMaker_cfg.py" on the sample /store/relval/CMSSW_12_0_1/RelValZEE_14/GEN-SIM-DIGI-RAW/PU_113X_mcRun4_realistic_v7_2026D76PU200-v2/10000/01dbe379-7211-4b82-b909-03b933277007.root. The ZEE, ZMM, and flat QCD samples from 12_1_0_pre5 also give this same error.

@tschuh verified this and might have more insight on the issue.

**Comment by cgsavard** [comment]
PR #183 was just created to hopefully fix this issue, great!

**Comment by tschuh** [comment]
Could you please verify that PR https://github.com/cms-L1TK/cmssw/pull/183 does fix it?

**Comment by tschuh** [comment]
Fix (https://github.com/cms-L1TK/cmssw/pull/183) got merged.
