### ISSUE TITLE
StubKiller Class logic broken

### ISSUE THREAD

**Issue by Chriisbrown** [cms-L1TK/cmssw#241]
Lines 

https://github.com/cms-L1TK/cmssw/blob/d52b66ba054cf42cd816a2961ae5159cb5db82b0/L1Trigger/TrackFindingTracklet/src/StubKiller.cc#L223

https://github.com/cms-L1TK/cmssw/blob/d52b66ba054cf42cd816a2961ae5159cb5db82b0/L1Trigger/TrackFindingTracklet/src/StubKiller.cc#L280

In the stubkiller class are currently checking if the list of layers/modukes to be killed is empty before killing the stubs so no stubs get killed, this was changed from if ( layersToKill.size() > 0 )  here: https://github.com/EmyrClement/StubKiller/blob/214e7b674ea94ada595abcc66a9296c49044acde/StubKiller.cc#L230
which checks if the list of layers/modules to be killed is not empty, I'm unsure why this was changed as it stops the stub killer from working

**Comment by emily-tsai11** [comment]
Hi Chris, thanks for pointing this out. I will make a PR later today with a fix.

**Comment by emily-tsai11** [comment]
PR submitted here: https://github.com/cms-L1TK/cmssw/pull/244

**Comment by Chriisbrown** [comment]
Can close this issue as it has been addressed in #244
