### ISSUE TITLE
Add approximate calculation for the displaced tracking

### ISSUE THREAD

**Issue by skinnari** [cms-L1TK/cmssw#44]
This PR (https://github.com/cms-L1TK/cmssw/pull/34) was closed since it needed to be updated to: 

(1) address code rules (https://twiki.cern.ch/twiki/bin/view/CMS/L1TrackCodeRules) 
(2) be made on top of the new development branch (L1TK-dev-11_2_0_pre6)

**Comment by tomalin** [comment]
This issue is addressed by the new PR https://github.com/cms-L1TK/cmssw/pull/52 .
