### ISSUE TITLE
Displaced tracking crashes

### ISSUE THREAD

**Issue by tomalin** [cms-L1TK/cmssw#58]
The displaced tracking crashes. I guess this is a result of the recent addition of the approximate floating point calculation. The crash occurs at https://github.com/cms-L1TK/cmssw/blob/L1TK-dev-11_2_0_pre6/L1Trigger/TrackFindingTracklet/src/MatchCalculator.cc#L271 because the statement " assert(std::abs(dphi) < 0.2);" fails.

I am running on /store/relval/CMSSW_11_2_0_pre5/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU25ns_110X_mcRun4_realistic_v3_2026D49PU200-v1/20000/0074C44A-BBE2-6849-965D-CB73FE0C0E6C.root . It crashes in the 5th event.

**Comment by skinnari** [comment]
@tomalin should we revert the merged PR if the code then crashes?

**Comment by tomalin** [comment]
@skinnari If you know how, yes, we should revert. Though we could perhaps wait a few days, in case Rutgers can submit a quick fix.

**Comment by gabhijith** [comment]
I have put a PR in place to fix it, The problem is discussed there along with the fix
https://github.com/cms-L1TK/cmssw/pull/59

Once the PR is approved, this issue can be closed.

**Comment by gabhijith** [comment]
@tomalin, Can this issue be closed as the PR is merged, or should we wait for a day or two to close it?

**Comment by tomalin** [comment]
This issue is closed, as it has been fixed by https://github.com/cms-L1TK/cmssw/pull/59 .

**Comment by tomalin** [comment]
This issue is closed, as it has been fixed by https://github.com/cms-L1TK/cmssw/pull/59 .
